#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

./vendor/bin/phpcs --config-set installed_paths "$SCRIPT_DIR/vendor/srggroup/srg_standards/src/CodeSniffer/Standards/SRG"

