FROM nginx:latest

RUN apt-get update;
RUN apt-get -y upgrade;

#Install some basic packages
RUN apt-get -y install \
	bash \
	wget \
	nano \
  	bash \
	ca-certificates \
	lsb-release \
	apt-transport-https;
